version: '3.8'

services:
  app:
    build: .
    container_name: habit_tracker
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/habit_tracker?schema=public
      - JWT_SECRET=your_jwt_secret_key
      - PORT=5000
    volumes:
      - .:/app
      - /app/node_modules  # This line makes node_modules a named volume instead of mounting from host

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=habit_tracker
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: