version: '3.8'

services:
  app:
    build: .
    container_name: habit_tracker
    ports:
      - "5002:5001"  # Change host port from 5001->5002
    environment:
      - PORT=5001
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=habit_tracker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: